<template>
  <div class="mapdiv" ref="mapdiv"></div>
</template>

<script lang="ts" setup>
import MapView from "@arcgis/core/views/MapView";
import { onMounted, ref } from "vue";
import Map from "@arcgis/core/Map";
import esriConfig from "@arcgis/core/config";

import CSVLayer from "@arcgis/core/layers/CSVLayer";
import GeoJSONLayer from "@arcgis/core/layers/GeoJSONLayer";
import Legend from "@arcgis/core/widgets/Legend";

const mapdiv = ref();

onMounted(() => {
  esriConfig.apiKey =
    "AAPK72621c47770b426798758730c48b8adeCpiJMaMF6zlMpNvLuvmd4H_yHgohLv9Jf0AAgDEbdZ1oVfvmLibxDgwZYfPgFIZf";

  //   const url =
  //     "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.csv";

  // create a geojson layer from geojson feature collection
  const geojson = {
    type: "FeatureCollection",
    metadata: {
      generated: 1705239963000,
      url: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_month.geojson",
      title: "USGS All Earthquakes, Past Month",
      status: 200,
      api: "1.10.3",
      count: 8973,
    },
    features: [
      {
        type: "Feature",
        properties: {
          mag: 5,
          place: "6 km E of Yorba Linda, CA",
          time: 1705239378160,
          updated: 1705239775883,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459679",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459679.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 22,
          net: "ci",
          code: "40459679",
          ids: ",ci40459679,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 57,
          dmin: 0.04369,
          rms: 0.21,
          gap: 30,
          magType: "ml",
          type: "earthquake",
          title: "M 1.2 - 6 km E of Yorba Linda, CA",
        },
        geometry: {
          type: "Point",
          coordinates: [-117.748, 33.8985],
        },
        id: "ci40459679",
      },
      {
        type: "Feature",
        properties: {
          mag: 5,
          place: "6 km E of Yorba Linda, CA",
          time: 1705239378160,
          updated: 1705239775883,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459679",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459679.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 22,
          net: "ci",
          code: "40459679",
          ids: ",ci40459679,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 57,
          dmin: 0.04369,
          rms: 0.21,
          gap: 30,
          magType: "ml",
          type: "earthquake",
          title: "M 1.2 - 6 km E of Yorba Linda, CA",
        },
        geometry: {
          type: "Point",
          coordinates: [-117.748, 33.8985],
        },
        id: "c1",
      },
      {
        type: "Feature",
        properties: {
          mag: 5,
          place: "6 km E of Yorba Linda, CA",
          time: 1705239378160,
          updated: 1705239775883,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459679",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459679.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 22,
          net: "ci",
          code: "40459679",
          ids: ",ci40459679,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 57,
          dmin: 0.04369,
          rms: 0.21,
          gap: 30,
          magType: "ml",
          type: "earthquake",
          title: "M 1.2 - 6 km E of Yorba Linda, CA",
        },
        geometry: {
          type: "Point",
          coordinates: [-117.748, 33.8985],
        },
        id: "c2",
      },
      {
        type: "Feature",
        properties: {
          mag: 5,
          place: "6 km E of Yorba Linda, CA",
          time: 1705239378160,
          updated: 1705239775883,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459679",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459679.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 22,
          net: "ci",
          code: "40459679",
          ids: ",ci40459679,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 57,
          dmin: 0.04369,
          rms: 0.21,
          gap: 30,
          magType: "ml",
          type: "earthquake",
          title: "M 1.2 - 6 km E of Yorba Linda, CA",
        },
        geometry: {
          type: "Point",
          coordinates: [-117.748, 33.8985],
        },
        id: "c3",
      },
      {
        type: "Feature",
        properties: {
          mag: 5,
          place: "6 km E of Yorba Linda, CA",
          time: 1705239378160,
          updated: 1705239775883,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459679",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459679.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 22,
          net: "ci",
          code: "40459679",
          ids: ",ci40459679,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 57,
          dmin: 0.04369,
          rms: 0.21,
          gap: 30,
          magType: "ml",
          type: "earthquake",
          title: "M 1.2 - 6 km E of Yorba Linda, CA",
        },
        geometry: {
          type: "Point",
          coordinates: [-117.748, 33.8985],
        },
        id: "c4",
      },
      {
        type: "Feature",
        properties: {
          mag: 5,
          place: "6 km E of Yorba Linda, CA",
          time: 1705239378160,
          updated: 1705239775883,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459679",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459679.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 22,
          net: "ci",
          code: "40459679",
          ids: ",ci40459679,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 57,
          dmin: 0.04369,
          rms: 0.21,
          gap: 30,
          magType: "ml",
          type: "earthquake",
          title: "M 1.2 - 6 km E of Yorba Linda, CA",
        },
        geometry: {
          type: "Point",
          coordinates: [-117.748, 33.8985],
        },
        id: "c5",
      },
      {
        type: "Feature",
        properties: {
          council: "DBKU",
          mag: 1.12,
          place: "8 km NW of The Geysers, CA",
          time: 1705239362240,
          updated: 1705239455928,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/nc73989021",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/nc73989021.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 19,
          net: "nc",
          code: "73989021",
          ids: ",nc73989021,",
          sources: ",nc,",
          types: ",nearby-cities,origin,phase-data,",
          nst: 22,
          dmin: 0.009205,
          rms: 0.02,
          gap: 51,
          magType: "md",
          type: "earthquake",
          title: "M 1.1 - 8 km NW of The Geysers, CA",
        },
        geometry: {
          coordinates: [110.34411723815202, 1.5728910594640553],
          type: "Point",
        },
        id: "dbku",
      },
      {
        type: "Feature",
        properties: {
          council: "MBKS",
          mag: 2.05999994,
          place: "10 km ENE of Pāhala, Hawaii",
          time: 1705237436330,
          updated: 1705237631920,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/hv73716617",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/hv73716617.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 65,
          net: "hv",
          code: "73716617",
          ids: ",hv73716617,",
          sources: ",hv,",
          types: ",origin,phase-data,",
          nst: 32,
          dmin: null,
          rms: 0.100000001,
          gap: 156,
          magType: "md",
          type: "earthquake",
          title: "M 2.1 - 10 km ENE of Pāhala, Hawaii",
        },
        geometry: {
          coordinates: [110.33889636154419, 1.547840144506651],
          type: "Point",
        },
        id: "mbks7",
      },
      {
        type: "Feature",
        properties: {
          council: "DBKU",
          mag: 1.12,
          place: "8 km NW of The Geysers, CA",
          time: 1705239362240,
          updated: 1705239455928,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/nc73989021",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/nc73989021.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 19,
          net: "nc",
          code: "73989021",
          ids: ",nc73989021,",
          sources: ",nc,",
          types: ",nearby-cities,origin,phase-data,",
          nst: 22,
          dmin: 0.009205,
          rms: 0.02,
          gap: 51,
          magType: "md",
          type: "earthquake",
          title: "M 1.1 - 8 km NW of The Geysers, CA",
        },
        geometry: {
          coordinates: [110.34516141347405, 1.5718472773128127],
          type: "Point",
        },
        id: "dbku8",
      },
      {
        type: "Feature",
        properties: {
          council: "MBKS",
          mag: 2.05999994,
          place: "10 km ENE of Pāhala, Hawaii",
          time: 1705237436330,
          updated: 1705237631920,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/hv73716617",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/hv73716617.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 65,
          net: "hv",
          code: "73716617",
          ids: ",hv73716617,",
          sources: ",hv,",
          types: ",origin,phase-data,",
          nst: 32,
          dmin: null,
          rms: 0.100000001,
          gap: 156,
          magType: "md",
          type: "earthquake",
          title: "M 2.1 - 10 km ENE of Pāhala, Hawaii",
        },
        geometry: {
          coordinates: [110.34463932581184, 1.548362041603852],
          type: "Point",
        },
        id: "mbks9",
      },
      {
        type: "Feature",
        properties: {
          council: "MPP",
          mag: 2.07999992,
          place: "13 km SE of Pāhala, Hawaii",
          time: 1705236220450,
          updated: 1705236406350,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/hv73716602",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/hv73716602.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 67,
          net: "hv",
          code: "73716602",
          ids: ",hv73716602,",
          sources: ",hv,",
          types: ",origin,phase-data,",
          nst: 31,
          dmin: null,
          rms: 0.119999997,
          gap: 186,
          magType: "md",
          type: "earthquake",
          title: "M 2.1 - 13 km SE of Pāhala, Hawaii",
        },
        geometry: {
          coordinates: [110.32636625768691, 1.4335416615057],
          type: "Point",
        },
        id: "mpp10",
      },
      {
        type: "Feature",
        properties: {
          council: "MPP",
          mag: 2.07999992,
          place: "13 km SE of Pāhala, Hawaii",
          time: 1705236220450,
          updated: 1705236406350,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/hv73716602",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/hv73716602.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 67,
          net: "hv",
          code: "73716602",
          ids: ",hv73716602,",
          sources: ",hv,",
          types: ",origin,phase-data,",
          nst: 31,
          dmin: null,
          rms: 0.119999997,
          gap: 186,
          magType: "md",
          type: "earthquake",
          title: "M 2.1 - 13 km SE of Pāhala, Hawaii",
        },
        geometry: {
          coordinates: [110.33315339727665, 1.432497812756452],
          type: "Point",
        },
        id: "mpp11",
      },
      {
        type: "Feature",
        properties: {
          council: "DBKU",
          mag: 1.12,
          place: "8 km NW of The Geysers, CA",
          time: 1705239362240,
          updated: 1705239455928,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/nc73989021",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/nc73989021.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 19,
          net: "nc",
          code: "73989021",
          ids: ",nc73989021,",
          sources: ",nc,",
          types: ",nearby-cities,origin,phase-data,",
          nst: 22,
          dmin: 0.009205,
          rms: 0.02,
          gap: 51,
          magType: "md",
          type: "earthquake",
          title: "M 1.1 - 8 km NW of The Geysers, CA",
        },
        geometry: {
          coordinates: [110.34255097517013, 1.573412950344462],
          type: "Point",
        },
        id: "dbku12",
      },
      {
        type: "Feature",
        properties: {
          council: "MBKS",
          mag: 2.05999994,
          place: "10 km ENE of Pāhala, Hawaii",
          time: 1705237436330,
          updated: 1705237631920,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/hv73716617",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/hv73716617.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 65,
          net: "hv",
          code: "73716617",
          ids: ",hv73716617,",
          sources: ",hv,",
          types: ",origin,phase-data,",
          nst: 32,
          dmin: null,
          rms: 0.100000001,
          gap: 156,
          magType: "md",
          type: "earthquake",
          title: "M 2.1 - 10 km ENE of Pāhala, Hawaii",
        },
        geometry: {
          coordinates: [110.33837427388437, 1.547840144506651],
          type: "Point",
        },
        id: "mbks13",
      },
      {
        type: "Feature",
        properties: {
          council: "MBKS",
          mag: 2.05999994,
          place: "10 km ENE of Pāhala, Hawaii",
          time: 1705237436330,
          updated: 1705237631920,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/hv73716617",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/hv73716617.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 65,
          net: "hv",
          code: "73716617",
          ids: ",hv73716617,",
          sources: ",hv,",
          types: ",origin,phase-data,",
          nst: 32,
          dmin: null,
          rms: 0.100000001,
          gap: 156,
          magType: "md",
          type: "earthquake",
          title: "M 2.1 - 10 km ENE of Pāhala, Hawaii",
        },
        geometry: {
          coordinates: [110.33863530772732, 1.547878740921007],
          type: "Point",
        },
        id: "mbks14",
      },
      {
        type: "Feature",
        properties: {
          council: "MBKS",
          mag: 2.05999994,
          place: "10 km ENE of Pāhala, Hawaii",
          time: 1705237436330,
          updated: 1705237631920,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/hv73716617",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/hv73716617.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 65,
          net: "hv",
          code: "73716617",
          ids: ",hv73716617,",
          sources: ",hv,",
          types: ",origin,phase-data,",
          nst: 32,
          dmin: null,
          rms: 0.100000001,
          gap: 156,
          magType: "md",
          type: "earthquake",
          title: "M 2.1 - 10 km ENE of Pāhala, Hawaii",
        },
        geometry: {
          coordinates: [110.33863530772732, 1.5479045671828828],
          type: "Point",
        },
        id: "mbks15",
      },
      {
        type: "Feature",
        properties: {
          council: "MBKS",
          mag: 2.05999994,
          place: "10 km ENE of Pāhala, Hawaii",
          time: 1705237436330,
          updated: 1705237631920,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/hv73716617",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/hv73716617.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 65,
          net: "hv",
          code: "73716617",
          ids: ",hv73716617,",
          sources: ",hv,",
          types: ",origin,phase-data,",
          nst: 32,
          dmin: null,
          rms: 0.100000001,
          gap: 156,
          magType: "md",
          type: "earthquake",
          title: "M 2.1 - 10 km ENE of Pāhala, Hawaii",
        },
        geometry: {
          coordinates: [110.33863530772732, 1.547895958428569],
          type: "Point",
        },
        id: "mbks16",
      },
      {
        type: "Feature",
        properties: {
          council: "around",
          mag: 0.89,
          place: "3 km NE of Colton, CA",
          time: 1705233717480,
          updated: 1705234096028,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459663",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459663.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 12,
          net: "ci",
          code: "40459663",
          ids: ",ci40459663,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 38,
          dmin: 0.1216,
          rms: 0.16,
          gap: 69,
          magType: "ml",
          type: "earthquake",
          title: "M 0.9 - 3 km NE of Colton, CA",
        },
        geometry: {
          coordinates: [110.31886811486248, 1.5736212347618022],
          type: "Point",
        },
        id: "around17",
      },
      {
        type: "Feature",
        properties: {
          council: "around",
          mag: 0.89,
          place: "3 km NE of Colton, CA",
          time: 1705233717480,
          updated: 1705234096028,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459663",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459663.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 12,
          net: "ci",
          code: "40459663",
          ids: ",ci40459663,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 38,
          dmin: 0.1216,
          rms: 0.16,
          gap: 69,
          magType: "ml",
          type: "earthquake",
          title: "M 0.9 - 3 km NE of Colton, CA",
        },
        geometry: {
          coordinates: [110.30937542910965, 1.557992061092122],
          type: "Point",
        },
        id: "around18",
      },
      {
        type: "Feature",
        properties: {
          council: "around",
          mag: 0.89,
          place: "3 km NE of Colton, CA",
          time: 1705233717480,
          updated: 1705234096028,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459663",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459663.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 12,
          net: "ci",
          code: "40459663",
          ids: ",ci40459663,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 38,
          dmin: 0.1216,
          rms: 0.16,
          gap: 69,
          magType: "ml",
          type: "earthquake",
          title: "M 0.9 - 3 km NE of Colton, CA",
        },
        geometry: {
          coordinates: [110.32277686781981, 1.5339898904400684],
          type: "Point",
        },
        id: "around19",
      },
      {
        type: "Feature",
        properties: {
          council: "around",
          mag: 0.89,
          place: "3 km NE of Colton, CA",
          time: 1705233717480,
          updated: 1705234096028,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459663",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459663.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 12,
          net: "ci",
          code: "40459663",
          ids: ",ci40459663,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 38,
          dmin: 0.1216,
          rms: 0.16,
          gap: 69,
          magType: "ml",
          type: "earthquake",
          title: "M 0.9 - 3 km NE of Colton, CA",
        },
        geometry: {
          coordinates: [110.34399581244003, 1.5284079515418227],
          type: "Point",
        },
        id: "around20",
      },
      {
        type: "Feature",
        properties: {
          council: "around",
          mag: 0.89,
          place: "3 km NE of Colton, CA",
          time: 1705233717480,
          updated: 1705234096028,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459663",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459663.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 12,
          net: "ci",
          code: "40459663",
          ids: ",ci40459663,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 38,
          dmin: 0.1216,
          rms: 0.16,
          gap: 69,
          magType: "ml",
          type: "earthquake",
          title: "M 0.9 - 3 km NE of Colton, CA",
        },
        geometry: {
          coordinates: [110.37024029657948, 1.5356644692716657],
          type: "Point",
        },
        id: "around21",
      },
      {
        type: "Feature",
        properties: {
          council: "around",
          mag: 0.89,
          place: "3 km NE of Colton, CA",
          time: 1705233717480,
          updated: 1705234096028,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459663",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459663.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 12,
          net: "ci",
          code: "40459663",
          ids: ",ci40459663,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 38,
          dmin: 0.1216,
          rms: 0.16,
          gap: 69,
          magType: "ml",
          type: "earthquake",
          title: "M 0.9 - 3 km NE of Colton, CA",
        },
        geometry: {
          coordinates: [110.38755048824464, 1.5585502478699311],
          type: "Point",
        },
        id: "around22",
      },
      {
        type: "Feature",
        properties: {
          council: "around",
          mag: 0.89,
          place: "3 km NE of Colton, CA",
          time: 1705233717480,
          updated: 1705234096028,
          tz: null,
          url: "https://earthquake.usgs.gov/earthquakes/eventpage/ci40459663",
          detail:
            "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci40459663.geojson",
          felt: null,
          cdi: null,
          mmi: null,
          alert: null,
          status: "automatic",
          tsunami: 0,
          sig: 12,
          net: "ci",
          code: "40459663",
          ids: ",ci40459663,",
          sources: ",ci,",
          types: ",nearby-cities,origin,phase-data,scitech-link,",
          nst: 38,
          dmin: 0.1216,
          rms: 0.16,
          gap: 69,
          magType: "ml",
          type: "earthquake",
          title: "M 0.9 - 3 km NE of Colton, CA",
        },
        geometry: {
          coordinates: [110.36688993690075, 1.5758539643234997],
          type: "Point",
        },
        id: "around23",
      },
    ],
  };

  // create a new blob from geojson featurecollection
  const blob = new Blob([JSON.stringify(geojson)], {
    type: "application/json",
  });

  // URL reference to the blob
  const url = URL.createObjectURL(blob);

  // Paste the url into a browser's address bar to download and view the attributes
  // in the CSV file. These attributes include:
  // * mag - magnitude
  // * type - earthquake or other event such as nuclear test
  // * place - location of the event
  // * time - the time of the event

  const template = {
    title: "{place}",
    content: "Magnitude {mag} {type} hit {place} on {time}.",
  };

  // The heatmap renderer assigns each pixel in the view with
  // an intensity value. The ratio of that intensity value
  // to the maxPixel intensity is used to assign a color
  // from the continuous color ramp in the colorStops property

  const renderer = {
    type: "heatmap",
    // radius: 20,
    colorStops: [
      { color: "rgba(0, 255, 0, 0)", ratio: 0 },
      { color: "rgba(255, 0, 0, 0.3)", ratio: 0.1 }, // Light green
      { color: "rgba(255, 69, 0, 0.7)", ratio: 0.2 }, // Light green
      { color: "rgba(255, 165, 0, 1)", ratio: 0.4 }, // Medium green
      { color: "rgba(255, 255, 0, 1)", ratio: 0.6 }, // Dark green
      { color: "rgba(0, 255, 0, 1))", ratio: 0.7 }, // Yellow
      { color: "rgba(0, 0, 255, 1)", ratio: 0.8 }, // Orange
      { color: "rgba(75, 0, 130, 1)", ratio: 0.9 }, // Dark Orange
      { color: "rgba(148, 0, 211, 1)", ratio: 1 }, // Red
    ],
    maxDensity: 0.01,
    minDensity: 0,
  };

  // create new geojson layer using the blob url
  const layer = new GeoJSONLayer({
    url,
    title: "Magnitude 2.5+ earthquakes from the last week",
    copyright: "USGS Earthquakes",
    popupTemplate: template,
    renderer: renderer,
    labelsVisible: true,
    labelingInfo: [
      {
        symbol: {
          type: "text", // autocasts as new TextSymbol()
          color: "white",
          font: {
            family: "Noto Sans",
            size: 8,
          },
          haloColor: "#472b77",
          haloSize: 0.75,
        },
        labelPlacement: "center-center",
        labelExpressionInfo: {
          expression: "Text($feature.mag, '#.0')",
        },
        where: "mag > 5",
      },
    ],
  });

  const map = new Map({
    basemap: "arcgis/dark-gray",
    layers: [layer],
  });

  const view = new MapView({
    container: mapdiv.value,
    center: [-138, 30],
    zoom: 2,
    map: map,
  });

  view.ui.add(
    new Legend({
      view: view,
    }),
    "bottom-left"
  );
});
</script>

<style scoped>
html,
body,
.mapdiv {
  padding: 0;
  margin: 0;
  height: 100%;
  width: 100%;
}
</style>
